version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sparkuser
      - POSTGRES_PASSWORD=sparkpass
      - POSTGRES_DB=sparkdb
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  python-producer:
    build:
      context: .
      dockerfile: Dockerfile-python
    container_name: python-producer
    depends_on:
      - kafka
    volumes:
      - ./producer:/app

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    ports:
      - "8080:8080" # Spark master UI
      - "7077:7077" # Spark master address
    environment:
      - SPARK_MODE=master

  spark-worker:
    image: bitnami/spark:latest
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

  spark-application:
    build:
      context: .
      dockerfile: Dockerfile-spark
    container_name: spark-application
    depends_on:
      - spark-master
      - kafka
      - postgres
   